name: release
on:
  release:
    types: [ published ]
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Get Release
        id: get
        uses: bruceadams/get-release@v1.2.0

      - name: Checkout the repository
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Zip binaries
        shell: bash
        run: |
          mv bin/linux/zetasql-formatter zetasql-formatter
          zip zetasql-formatter_linux_x86_64.zip zetasql-formatter
          mv bin/osx/zetasql-formatter zetasql-formatter
          zip zetasql-formatter_darwin_amd64.zip zetasql-formatter

      - name: Upload Linux Asset
        id: upload-linux-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get.outputs.upload_url }}
          asset_path: zetasql-formatter_linux_x86_64.zip
          asset_name: zetasql-formatter_linux_x86_64.zip
          asset_content_type: application/zip

      - name: Upload OSX Asset
        id: upload-osx-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get.outputs.upload_url }}
          asset_path: zetasql-formatter_darwin_amd64.zip
          asset_name: zetasql-formatter_darwin_amd64.zip
          asset_content_type: application/zip
